# Generated by Django 3.1.2 on 2020-10-31 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('date', models.DateField(auto_now=True)),
                ('filename', models.CharField(max_length=100)),
            ],
        ),
    ]
